version: '3.3'

services:
  #A database service: Hawani



  #A dashboard service: Plai



  #A messaging service: Hassan



  #An analysis service: Pierre
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
     - ./notebooks/:/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks

# volumes:
  