version: '3.3'

services:
  #A database service: Hawani
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: password
      volumes:
          - "./db:/db"
      ports:
        - 8080:8080

  #A dashboard service: Plai
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
      


  #A messaging service: Hassan



  #An analysis service: Pierre
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
     - ./notebooks/:/notebooks
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks

# volumes:
  
