version: '3.3'

services:
  #A database service: Hawani
  db:
      image: mysql
      container_name: mysqldb_container
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: user
      ports:
        - 3306:3306
      expose:
        - '3306'
      volumes:
          - ./db:/docker-entrypoint-initdb.d
